### ISSUE TITLE
(Layan Aurorae) Border Issue 

### ISSUE THREAD

**Issue by Syntist** [vinceliuice/Layan-kde#4]
This issue is kinda Annoying because, I can't resize the application from Left and Right, I have seen border size is set to 0, but setting it gives a weird border.. Which doesn't really suits the Theme.

Breeze on the other hand.. work perfect even with no border, I can still resize the Window. 
Layan Aurorae:
![image](https://user-images.githubusercontent.com/24858150/73198787-7dfd4f80-4155-11ea-88db-6c5fe364dea4.png)

Breeze Aurorae (Set to No Border):
![image](https://user-images.githubusercontent.com/24858150/73198868-a127ff00-4155-11ea-9221-bfc05a77133a.png)

I love the theme. but this one issue is quite annoying

And one more thing Blur look quite Weird too when there is something dark behind it
![image](https://user-images.githubusercontent.com/24858150/73199027-e8ae8b00-4155-11ea-998d-973dad5fd6e3.png)

**Comment by vinceliuice** [comment]
I'll fix this issue

**Comment by PoorPocketsMcNewHold** [comment]
![Peek 17-02-2020 09-35](https://user-images.githubusercontent.com/13170204/74637538-13db3780-5162-11ea-9fe3-39434e9730cb.gif)
Seems to have been fixed.

**Comment by vinceliuice** [comment]
Yes, I fixed this

**Comment by HuM4NoiD** [comment]
![image](https://user-images.githubusercontent.com/41481260/165596930-291a63c5-a3ee-4c66-a68f-95caf49b962b.png)

I still have a part of the border where the background is not blurred.
